[build]
  command = "pnpm install && pnpm run build:client"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# Handle API requests
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
